# Generated by Django 4.2.20 on 2025-11-11 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Unique identifier for the email template', max_length=100, unique=True)),
                ('subject', models.CharField(help_text='Email subject line', max_length=255)),
                ('body', models.TextField(help_text='Email body with placeholders like {user_name}, {course_name}, etc.')),
            ],
        ),
    ]
