# Generated by Django 4.2.20 on 2025-11-11 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_emailtemplate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmailTemplate',
        ),
    ]
